---
- name: Install curl
  become: yes
  hosts: hostsaws

  tasks:
    - name: Install curl and vim on Ubuntu Debian
      ansible.builtin.apt:
        name:
          - curl
          - vim
        state: present
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: Install curl and nano on CentOS RedHat
      ansible.builtin.yum:
        name:
          - curl
          - nano
          - git
        state: present
      when: ansible_distribution in ["CentOS", "RedHat"]
